[passwords]
"rafael.ramirez"  = "RAZ21"
"usuario_UREP"="UREP"
"maria.zelaya" = "maria.zelaya"
"pilar.hernandez" = "pilar.hernandez"
"leo.merino"="leo.merino"
"jose.quezada"="jose.quezada"
"samuel.marquez"="samuel.marquez"
"katya.flamenco"="katya.flamenco"
